### ISSUE TITLE
Сменить название

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#100]
текущее дискредитировано

**Comment by asosnoviy** [comment]
Украли, сволочи!

**Comment by tsukanov-as** [comment]
Главное новое не крадите )

ps Ну а вообще представь я сейчас выкачу BSL LS. Тоже ведь имею полное право. Разве это не воровство будет?

**Comment by asosnoviy** [comment]
Честно честно не специально, просто так совпало =(
