### ISSUE TITLE
Добавить кэш АСД в консоль

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#127]
Если исходник и парсер не менялись, то брать АСД из кэша

**Comment by tsukanov-as** [comment]
Плюс наверно стоит настройку сделать "Использовать кэш АСД".
Чтобы например иметь возможность делать замер как отдельно плагинов, так и вместе с разбором

**Comment by wwall** [comment]
а как определять что поменялось?

**Comment by tsukanov-as** [comment]
А в чем сложность? Хэш SHA1 взять и все.

Вот например в радаре я так делал: https://github.com/lead-tools/old_radar/blob/master/src/CommonModules/Git_sc/Ext/Module.bsl
Хэш идентичный гитовому.
