### ISSUE TITLE
Убрать проверку каноничности из лексера

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#138]
Сейчас с таблицей токенов это можно делать плагином.

**Comment by tsukanov-as** [comment]
Надо только понять насколько плагин будет тормознее и будет ли

**Comment by wwall** [comment]
Реально лучше тогда два лексера иметь - один без проверок, второй с проверками. 
Кто его знает что там может понадобиться дальше

**Comment by tsukanov-as** [comment]
Возможно, но если сейчас получится канон быстро плагином чекать, то добавление лексера можно отложить пока реальная необходимость не возникнет

**Comment by tsukanov-as** [comment]
Возможно я туплю, но разницы во времени будто вообще нет
