### ISSUE TITLE
Добавить разбор препроцессора

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#19]
Парсить по аналогии с обычным If Then. Все возможности это не покроет, но при нормальном стиле кодинга 99.99% будет разбираться без ошибок. Оставшиеся ошибки разбора пусть будут сигналом переписать это дерьмо (любая интерпретация фразы верна)

**Comment by tsukanov-as** [comment]
В этом варианте на 3000 модулей поймал всего 4 ошибки разбора. Все они относятся к случаю когда в препроцессор заключена ветка ElsIf.
В принципе можно выделить ElsIf в отдельный тип узла и внутри препроцессора разбирать его как Statement.
Плюс еще нужно выделить фиктивный скоп для символов препроцессора, и наложить ограничения на выражения препроцессора.

**Comment by tsukanov-as** [comment]
Прогнал на ERP 2.2.3.144
Заняло чуть больше 30 минут.
Всего 12 ошибок (все из-за извращений с препроцессором в коде):
- 11 ошибок типа "already declared"
- 1 ошибка типа "Expected EndIf"

**Comment by tsukanov-as** [comment]
> все из-за извращений с препроцессором в коде

Однако это не совсем так. В случае "already declared" там реально дважды определена функция. Синтаксический контроль в платформе спокойно пропускает несколько объявлений функций с одним именем, если у них стоит директива `&НаСервереБезКонтекста`. Т.е. это не только ошибка в модулях, а еще и в платформе. При вызове функции, которая определена несколько раз, похоже берется первое по порядку определение (но это не точно).

**Comment by AGPonomarev** [comment]
Замеры:
проц i5-4570, 4 ядра без HT 3,2Гц

ERP 2.4.1.189
Платформа x86 8.3.11.2528
MaxJobs = 8; ChunkSize = 50
21 минута.

Платформа x64 8.3.11.2528
MaxJobs = 8; ChunkSize = 50
18 минут.

Платформа x64 8.3.11.2528
MaxJobs = 16; ChunkSize = 50
16 минут

3 ошибки Expected EndIf
15 ошибок Method already 
2 ошибки Expected Then
3 ошибки Identifier already declared

**Comment by tsukanov-as** [comment]
Что-то мало у тебя ошибок. Их там под сотню должно быть

**Comment by tsukanov-as** [comment]
Этого пока хватит. Куда плыть дальше будет понятно позже
