### ISSUE TITLE
Вместо Goto-транслятора сделать While-транслятор

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#40]
Надо таки наверно вернуться к этой заготовке и добить ее 😄 
Уже в самом начале стало понятно, что идея с Goto была плохой. Проблема в возвратах из процедур - для них придется городить большой If, в котором будут все возможные места возврата. Вариант рабочий, но дюже некрасивый. Потому я на него забил.
Вызов процедур лучше организовать на состояниях в цикле по аналогии с машиной Тьюринга.

**Comment by dmpas** [comment]
Попробовал я как-то в While-цикл- скомпилировать руками код с двумя вложенными вызовами функций... и решил, что Goto надёжнее и проще

**Comment by tsukanov-as** [comment]
@dmpas, а возвраты как с Goto делать кроме большого If?
Были бы метки вычисляемые...
Ну а во вложенных вызовах не вижу проблемы. Держать все переменные в стеке да и все. Там конечно есть нюансы (передача по ссылке, например), но вроде как все решаемые.

**Comment by dmpas** [comment]
@tsukanov-as не понял, в чём затык с возвратами?

**Comment by tsukanov-as** [comment]
@dmpas, каждый вызов процедуры нужно помечать, чтобы вернуться после вызова обратно.
А так как метки невычисляемые, то нужен какой-то диспетчер (большой If) который сделает выбор метки для возврата (см. ~return:).
Очень приблизительный псевдокод:
```bsl
~func1:

// ...
adr = "f1_1"; 
goto ~func2;
~f1_1: // для возврата после вызова
// ...
adr = "f1_2";
goto ~func2;
~f1_2: // для возврата после вызова
// ...
adr = "f1_3";
goto ~func2;
~f1_3: // для возврата после вызова
// ...

goto ~return;

// конец функции func1

~func2:

// ...

goto ~return;

// конец функции func2

~return:

if adr = "f1_1" then
	goto ~f1_1;
elsif adr = "f1_2" then
	goto ~f1_2;
elsif adr = "f1_3" then
	goto ~f1_3;
endif;
```
Можно еще конечно дублировать объявление процедуры под каждый вызов... Будет эффективно, т.к. каждый дубликат будет безусловно возвращаться только в одну точку. Но вариант тоже не очень красивый.

**Comment by tsukanov-as** [comment]
Чет я подумал подумал.... Все же вариант с дубликатами не так уж и плох. Дубликатов должно быть не очень много.
А некоторые вызовы так вообще инлайнить можно. Правда не совсем понятно как принимать решение инлайнить или нет.

**Comment by tsukanov-as** [comment]
С Goto еще один трабл: он не умеет прыгать внутрь IF, WHILE и прочих конструкций. Получается, что вернуться из процедуры внутри этих конструкций нельзя. Значит нужно их все заменять на код с Goto... Видимо извратиться таки можно, но мне пока лень

**Comment by tsukanov-as** [comment]
Вернувшись снова к этому таску пришел к выводу, что меня не устроит ни Goto ни While.
Хочется не просто иметь возможность выполнить произвольный код, а еще и иметь пошаговое выполнение. В связи с этим видимо попробую сделать интерпретатор, а этот таск стал пока не актуален.
