### ISSUE TITLE
Ошибка парсинга

### ISSUE THREAD

**Issue by akabrr** [lead-tools/bsparser#55]
Вот такая конструкция вызывает ошибку

`#Если Клиент Тогда`
`ИначеЕсли  КакоеТоУсловие Тогда`

**Comment by tsukanov-as** [comment]
@akabrr 
Да, такие вещи не разбираются. Это сложновато сделать, а встречается такой код очень редко.
Например, на всю ERP вроде ни разу не встретилось.
Так что я решил пока не заморачиваться этим.
Анализ инструкций препроцессора сознательно сделан не полным, т.к. для полного разбора этот анализ должен выполняться до основного парсинга. А это увеличит время разбора в несколько раз.... В общем тут компромиссное решение )

**Comment by akabrr** [comment]
Спасибо за ответ, в самописной конфигурации, которую мне теперь приходиться сопровождать, такого кода много.

**Comment by tsukanov-as** [comment]
@akabrr На текущей версии должно нормально разбираться
