### ISSUE TITLE
Баг AfterVisitVisitPrepExpr

### ISSUE THREAD

**Issue by akabrr** [lead-tools/bsparser#57]
В процедуре VisitPrepExpr добавлен цикл:

	For Each Hook In Visitor.Hooks.AfterVisitVisitPrepExpr Do
		Hook.AfterVisitVisitPrepExpr(PrepExpr, Visitor.Stack, Visitor.Counters);
	EndDo;

Похоже ошибка, наверное имелось ввиду  AfterVisitPrepExpr.

**Comment by tsukanov-as** [comment]
Спасибо!
