### ISSUE TITLE
Убрать поддержку синтаксиса onescript

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#78]
лучше один язык парсить правильно

**Comment by khorevaa** [comment]
(( Я только вник и даже плагин начал писать

**Comment by tsukanov-as** [comment]
Я же писал об этом в чате ) Давай обсудим

Ты плагин пишешь для анализа кода библиотек на onescript?

**Comment by khorevaa** [comment]
Да для документатора по комментариям модуля [тут](https://github.com/khorevaa/oscript-documentator/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8.os)
Да модули на oscript

**Comment by tsukanov-as** [comment]
@khorevaa Насколько вижу ты русскую версию парсера используешь. Этот таск не касается того форка (который волен поддерживать синтаксис onescript хоть полностью). Или в планах английскую тоже использовать?

ps Тут еще трабл в том, что я вообще не разбираю аннотации onescript и не собираюсь это делать, т.к. полная поддержка синтаксиса onescript в принципе не планировалась и не заявлялась. А без такой поддержки рано или поздно ты столкнешься с тем, что парсер подавится модулем onescript :)

**Comment by tsukanov-as** [comment]
упс не туда коммит подвязал

**Comment by khorevaa** [comment]
По аннотациям уже сделал изменения. Теперь не давится.. и да я использую русский форк у меня который в репе... наверное тут можно дропать поддерку оскрипт

**Comment by tsukanov-as** [comment]
ok )
