### ISSUE TITLE
Документация по проекту

### ISSUE THREAD

**Issue by LazarenkoA** [lead-tools/bsparser#96]
Идея просто супер, реализация с применением паттернов очень нравится!
Только почему на анг? Еще все же недостаточно инфы, например что плагин вызывается через метод Go() я не нашел в документации, самому пришлось расследовать.

**Comment by tsukanov-as** [comment]
Спасибо )
На анг я пишу по работе, и лично для меня русский значения вообще не имеет.
Что так, что так - все едино. Но с английским чуток удобнее и в целом перспективнее сразу делать на нем.

Я возьму на заметку про документацию, но на самом деле я постарался сделать все настолько простым, чтобы документация не требовалась вообще.

Типа смотришь примеры. Делаешь по аналогии. Все возможности станут понятны со временем.
Если возникает затруднение, я всегда отвечу и помогу. Но еще раз акцентирую: там все очень просто.

> самому пришлось расследовать

Я надеялся что именно так и будет, и что самого кода будет достаточно для понимания )

**Comment by tsukanov-as** [comment]
Еще кстати насчет Go() я добавлял пример во введении: https://github.com/Lead-Tools/BSL-Parser/blob/master/oscript/test.os

**Comment by tsukanov-as** [comment]
@LazarenkoA 
Начал формировать документацию в файле: https://github.com/lead-tools/bsparser/blob/dev/book.md
