### ISSUE TITLE
Перевести код на русский

### ISSUE THREAD

**Issue by tsukanov-as** [lead-tools/bsparser#99]

**Comment by asosnoviy** [comment]
Уже же был русский форк?

**Comment by tsukanov-as** [comment]
> Уже же был русский форк?

После этого баги правились (и не только). Надо сравнивать в чем отличие, мне проще с нуля сделать, чтоб ошибок избежать.

Кроме того речь не идет о новом форке. Я решил мувнуть этот проект на русский, так может быть хоть кому то польза будет от проекта.

**Comment by tsukanov-as** [comment]
Еще сделаю мультипоток для ванскрипта и будет вундервафля для адептов оного )

**Comment by tsukanov-as** [comment]
йа асилил
